# Generated by Django 4.2.4 on 2023-09-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('tour_dates', models.CharField(max_length=100)),
                ('preferences', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
