# Generated by Django 4.2.4 on 2023-09-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_trip_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='tour_dates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
