# Generated by Django 4.2.4 on 2023-09-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_trip_tour_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.TextField()),
                ('tour_dates', models.CharField(max_length=100)),
                ('preferences', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='trip',
        ),
    ]
