# Generated by Django 4.2.4 on 2023-09-05 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_trips_delete_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='locs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.TextField()),
                ('tour_dates', models.CharField(max_length=100)),
                ('preferences', models.TextField()),
                ('add_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.trips')),
            ],
        ),
    ]
