# Generated by Django 4.2.4 on 2023-09-05 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_locs'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
