# Generated by Django 4.2.4 on 2023-09-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trip',
        ),
    ]
