# Generated by Django 4.2.4 on 2023-09-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
